let suggestions = [
    "Ropa Nueva",
    "Ropa Usada",
    "Ropa de Hombre",
    "Ropa de Mujer",
    "Ropa de Niño",
    "Ropa de Niña",
    "Ropa de Bebé",
    "Accesorios",
    "Outfits",
    "Zapatos",
    "Bolsos",
    "Camisetas",
    "Pantalones",
    "Vestidos",
    "Chaquetas",
    "Abrigos",
    "Sombreros",
    "Bufandas",
    "Calcetines",
    "Gafas de Sol",
    "Joyas",
    "Novedades",
    "Ofertas",
    "Inspiración",
    "Trajes de Baño",
    "Ropa Deportiva",
    "Lenceria",
    "Formal",
    "Ropa de Trabajo",
    "Playa",
    "Ropa de Invierno",
    "Ropa de Verano",
    "Ropa de Primavera",
    "Ropa de Otoño",
    "Ropa Vintage",
    "Tallas Grandes",
    "Ropa Juvenil"
];